    create table Game (
        gauid bigint generated by default as identity (start with 1),
        board varchar(255),
        created datetime,
        description varchar(255),
        lastStep datetime,
        modified datetime,
        name varchar(255),
        state varchar(255),
        type varchar(255),
        black_uuid bigint,
        white_uuid bigint,
        primary key (gauid)
    );

    create table Step (
        suid bigint generated by default as identity (start with 1),
        created datetime,
        step varchar(255),
        game_gauid bigint,
        user_uuid bigint,
        primary key (suid)
    );

    create table User (
        uuid bigint generated by default as identity (start with 1),
        created datetime,
        email varchar(255),
        enabled boolean,
        firstName varchar(255),
        lastLogin datetime,
        lastName varchar(255),
        login varchar(255),
        modified datetime,
        password varchar(255),
        role varchar(255),
        primary key (uuid)
    );

    alter table Game 
        add constraint FK21C0122BE6E7CF 
        foreign key (white_uuid) 
        references User;

    alter table Game 
        add constraint FK21C012BADC19B9 
        foreign key (black_uuid) 
        references User;

    alter table Step 
        add constraint FK277AEC559BF88E 
        foreign key (game_gauid) 
        references Game;

    alter table Step 
        add constraint FK277AEC30BA3D6D 
        foreign key (user_uuid) 
        references User;
